### ISSUE TITLE
[FEATURE] csi dashboard roadmap

### ISSUE THREAD

**Issue by zxh326** [juicedata/juicefs-csi-driver#916]
TODO:

- [x] basic auth
- [ ] overview dashboard
- [ ] PV/PVC CRUD

---
TBD

- [ ] easy warmup
- [ ] easy create cache cluster
- [x] dynamically modify some config
